default: compile pointers

compile: compile.cc
	clang++ -Wall -Wextra -pedantic -std=c++14 compile.cc -o compile

pointers: pointers.cc
	clang++ -Wall -Wextra -Wno-unused-variable -pedantic -std=c++14 pointers.cc -o pointers
