default: interfaces special raii zero

interfaces: interfaces.cc
	clang++ -std=c++14  -Wall interfaces.cc -o interfaces

special: special.cc
	clang++ -std=c++14  -Wall -Wdeprecated special.cc -o special

raii: raii.cc
	clang++ -std=c++14  -Wall -Wdeprecated raii.cc -o raii

zero: zero.cc
	clang++ -std=c++14  -g -Wall -Wdeprecated zero.cc -o zero
