default: concepts emulate introspect

concepts: concepts.cc
	clang++ -std=c++14  -g -Wall -Wdeprecated concepts.cc -o concepts

emulate: emulate.cc
	clang++ -std=c++14  -g -Wall -Wdeprecated emulate.cc -o emulate

introspect: introspect.cc
	clang++ -std=c++14  -g -Wall -Wdeprecated introspect.cc -o introspect
